# Generated by Django 5.1.4 on 2025-02-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postmedia_delete_postimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmedia',
            options={'verbose_name_plural': 'Post Media'},
        ),
    ]
